version: "2.4"

services:
  app:
    cpus: 1
    image: "arensonz/todo-api"
    ports:
      - 5122:5122
    working_dir: "/app"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5122"
      NPGSQL_CONN: "Host=postgres;Username=postgres;Password=0000;Database=postgres;Port=5432"
    depends_on:
      - "postgres"
    restart: on-failure

  postgres:
    cpus: 1
    image: postgres:14.4
    ports:
      - 5432:5432
    working_dir: "/"
    volumes:
      - "./Databases:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '0000'
      POSTGRES_DB: postgres
    restart: on-failure

  server-1:
    image: httpd
    cpus: 0.5
    mem_limit: 50m
    memswap_limit: 100m
    mem_reservation: 25m
    volumes:
      - "./server.conf:/usr/local/apache2/conf/httpd.conf"
      - "todo_client_1:/var/www/todo-app"
    working_dir: "/"
    expose: 
      - "80"
    command: 
      - /bin/sh
      - -c
      - |
        sed -i 's/<h1 class="header__name">Get Things Done!<\/h1>/<h1 class="header__name">Get Things Done! - Server 01<\/h1>/' /var/www/todo-app/index.html
        httpd-foreground

  server-2:
    image: httpd
    cpus: 0.5
    cpuset: "1"
    volumes:
      - "./server.conf:/usr/local/apache2/conf/httpd.conf"
      - "todo_client_2:/var/www/todo-app"
    working_dir: "/"
    expose: 
      - "80"
    command: 
      - /bin/sh
      - -c
      - |
        sed -i 's/<h1 class="header__name">Get Things Done!<\/h1>/<h1 class="header__name">Get Things Done! - Server 02<\/h1>/' /var/www/todo-app/index.html
        httpd-foreground

  proxy-nginx:
    cpus: 2
    image: nginx
    ports:
      - 80:80
    volumes:
      - "./proxy-nginx.conf:/etc/nginx/nginx.conf"
    working_dir: "/"
    depends_on:
      - "server-1"
      - "server-2"
    restart: on-failure

volumes:
  todo_client_1:
  todo_client_2:
  todo_client_3:
  todo_client_4:
  todo_client_5:
  todo_client_6:
  todo_client_7:
  todo_client_8:
  todo_client_9:
  todo_client_10:
