version: "3.8"

services:
  app:
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 150M
        reservations:
          cpus: '0.05'
          memory: 75M
    image: "arensonz/todo-api"
    ports:
      - 5122:5122
    working_dir: "/app"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5122"
      NPGSQL_CONN: "Host=postgres;Username=postgres;Password=0000;Database=postgres;Port=5432"
  postgres:
    image: postgres:14.4
    ports:
      - 5432:5432
    working_dir: "/"
    volumes:
      - "./TodoApi/Databases:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '0000'
      POSTGRES_DB: postgres
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "../todo_client:/var/www/todo-app"
    working_dir: "/"

