version: "2.4"

services:
  app:
    cpu_count: 1
    cpu_percent: 50
    image: "todo-api"
    ports:
      - 5122:5122
    working_dir: "/app"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5122"
      NPGSQL_CONN: "Host=postgres;Username=postgres;Password=0000;Database=postgres;Port=5432"
    depends_on:
      - "postgres"
    restart: on-failure

  postgres:
    cpu_count: 1
    cpu_percent: 50
    image: postgres:14.4
    ports:
      - 5432:5432
    working_dir: "/"
    volumes:
      - "./Databases:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '0000'
      POSTGRES_DB: postgres
    restart: on-failure

  server-1:
    image: httpd
    cpu_count: 1
    cpu_percent: 10
    volumes:
      - "./server.conf:/usr/local/apache2/conf/httpd.conf"
      - "todo_client_1:/var/www/todo-app"
    working_dir: "/"
    ports:
      - 8080:80
    command: 
      - /bin/sh
      - -c
      - |
        sed -i 's/<h1 class="header__name">Get Things Done!<\/h1>/<h1 class="header__name">Get Things Done! - Server 01<\/h1>/' /var/www/todo-app/index.html
        httpd-foreground

  server-2:
    image: httpd
    cpu_count: 1
    cpu_percent: 10
    volumes:
      - "./server.conf:/usr/local/apache2/conf/httpd.conf"
      - "todo_client_2:/var/www/todo-app"
    working_dir: "/"
    ports:
      - 8081:80
    command: 
      - /bin/sh
      - -c
      - |
        sed -i 's/<h1 class="header__name">Get Things Done!<\/h1>/<h1 class="header__name">Get Things Done! - Server 02<\/h1>/' /var/www/todo-app/index.html
        httpd-foreground

  server-3:
    image: httpd
    cpu_count: 1
    cpu_percent: 10
    volumes:
      - "./server.conf:/usr/local/apache2/conf/httpd.conf"
      - "todo_client_3:/var/www/todo-app"
    working_dir: "/"
    ports:
      - 8082:80
    command: 
      - /bin/sh
      - -c
      - |
        sed -i 's/<h1 class="header__name">Get Things Done!<\/h1>/<h1 class="header__name">Get Things Done! - Server 03<\/h1>/' /var/www/todo-app/index.html
        httpd-foreground

  server-4:
    image: httpd
    cpu_count: 1
    cpu_percent: 10
    volumes:
      - "./server.conf:/usr/local/apache2/conf/httpd.conf"
      - "todo_client_4:/var/www/todo-app"
    working_dir: "/"
    ports:
      - 8083:80
    command: 
      - /bin/sh
      - -c
      - |
        sed -i 's/<h1 class="header__name">Get Things Done!<\/h1>/<h1 class="header__name">Get Things Done! - Server 04<\/h1>/' /var/www/todo-app/index.html
        httpd-foreground

volumes:
  todo_client_1:
  todo_client_2:
  todo_client_3:
  todo_client_4:
